### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by syou1219** [syou1219/favorite_scene#26]
### 実装予定の機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] クリップ投稿機能
- [x] タグ機能
- [x] カテゴリ機能
- [x] 検索機能（マルチ検索可)
- [x] オートコンプリート機能
- [x] コメント機能
- [x] いいね機能
- [ ] ランキング機能
- [ ] 通知機能

### 必要なページ
- [x] トップページ
- [x] ログインページ
- [x] 会員登録ページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] お問い合わせページ
- [x] 投稿一覧ページ
- [x] 投稿詳細ページ
- [x] 投稿作成ページ
- [x] 投稿編集ページ
- [ ] マイページ
- [ ] いいね一覧ページ
- [ ] ユーザー情報変更ページ
- [ ] パスワードリセットページ
- [ ] 検索結果一覧ページ(タイトル・タグ・カテゴリ)

**Comment by kenchasonakai** [comment]
個人開発におけるプロジェクトマネジメントで作成したGitHubProjectをpublicに変更後、GitHubProjectのURLの提出もお願いしたいです

**Comment by syou1219** [comment]
レビューありがとうございます。
以下GitHubProjectのURLとなります
URL: https://github.com/users/syou1219/projects/3

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
レビューしてこちらのコメントを後程更新します。

**Comment by syou1219** [comment]
ありがとうございます！！
よろしくお願いします！！

**Comment by Tsuchiya2** [comment]
↑のコメント更新しました。

**Comment by kenchasonakai** [comment]
LGTMです！
