### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by syou1219** [syou1219/favorite_scene#56]
## 各種情報
サービス名
FavoriteScene
サービスURL
https://favorite-scene.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 投稿機能
- [x] タグ機能
- [x]  カテゴリ機能
- [x] 検索機能
- [x] コメント機能
- [x] いいね機能
- [x] ランキング機能(いいね数)
- [x] オートコンプリート機能

## READMEレビュー時から変更した機能
・検索機能のマルチ検索を予定していましたが、オートコンプリート機能を検索機能に実装したため、マルチ検索機能は省きました。
・パスワードリセット機能は開発環境では作成できましたが、本番環境ではうまくいかなかったため、本リリース時に実装を考えています。

## 本リリース時に実装したい機能
- [ ] 通知機能
- [ ] ランキング機能(タグ毎のランキング)
- [ ] パスワードリセット機能

### トップページ

![Image](https://github.com/syou1219/favorite_scene/assets/74698888/fe277d36-daf0-4693-a985-8ce8bf225f84)

### 投稿一覧ページ

![Image](https://github.com/syou1219/favorite_scene/assets/74698888/a2ded5c7-d4b0-4634-8b4f-2f59284c338d)

### 投稿詳細ページ

![Image](https://github.com/syou1219/favorite_scene/assets/74698888/876c98d5-389f-4605-925b-fa8dde6d126c)

### 投稿作成ページ

<img width="1440" alt="スクリーンショット 2024-05-03 17 58 50" src="https://github.com/syou1219/favorite_scene/assets/74698888/683e9c15-e089-4b35-a499-3d7ee7e0e538">

### マイページ

![Image](https://github.com/syou1219/favorite_scene/assets/74698888/e07d3b75-9f61-4d8e-9773-77bf313f394f)

**Comment by kenchasonakai** [comment]
LGTMです！
